//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/AllMain/PlayerInput/MyPlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MyPlayerInput : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MyPlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MyPlayerInput"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""74284075-c81b-4e10-9700-65c0fd4fb6bc"",
            ""actions"": [
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""32e08763-53a0-4f7a-96d3-e66a50961c1d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Block"",
                    ""type"": ""Button"",
                    ""id"": ""500bea2e-36dc-4d79-91f2-8751763053a2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GetSword"",
                    ""type"": ""Button"",
                    ""id"": ""622cec1d-7e2d-44ef-8a61-086d0eb026c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GetAxe"",
                    ""type"": ""Button"",
                    ""id"": ""c4a55fe5-2737-4653-94dc-eb9b7a8b1b4e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""GetMace"",
                    ""type"": ""Button"",
                    ""id"": ""93e6f69a-b3d9-455e-a687-47364e526c6f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ExitToMenu"",
                    ""type"": ""Button"",
                    ""id"": ""f24eda40-2308-4432-8d6d-75519b92a1d6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Kick"",
                    ""type"": ""Button"",
                    ""id"": ""136745f2-bfce-4a42-81f6-4a5f712fbf6d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenStats"",
                    ""type"": ""Button"",
                    ""id"": ""f80e2d3e-ea9d-43e6-ada7-1b86c4cbc0a4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StartDialog"",
                    ""type"": ""Button"",
                    ""id"": ""15780626-5a83-4c81-87e6-d41b38e37e88"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""22369728-0dad-4c01-91d2-9c33fb294f33"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30e5b4fd-a24e-46fb-b4e6-34c08a0b99b3"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GetSword"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dcfd9f05-3f98-4f4f-983a-1c9f1658bb1d"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GetAxe"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bdcb67ba-e1e3-4c33-9ce6-eb191a023320"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GetMace"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""14f6c981-0300-48f9-813c-534c2408d7fd"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Block"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e1dde6df-01ee-4c58-84f2-dfc75f0bdcf0"",
                    ""path"": ""<Keyboard>/backquote"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ExitToMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""661afa52-27c8-4580-b9b5-c661ec6f68b2"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Kick"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""337776e3-8363-4496-b81b-aea7db2b1b36"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenStats"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7858f6f-72af-43dd-8b53-cc0fac9671ed"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartDialog"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Attack = m_Player.FindAction("Attack", throwIfNotFound: true);
        m_Player_Block = m_Player.FindAction("Block", throwIfNotFound: true);
        m_Player_GetSword = m_Player.FindAction("GetSword", throwIfNotFound: true);
        m_Player_GetAxe = m_Player.FindAction("GetAxe", throwIfNotFound: true);
        m_Player_GetMace = m_Player.FindAction("GetMace", throwIfNotFound: true);
        m_Player_ExitToMenu = m_Player.FindAction("ExitToMenu", throwIfNotFound: true);
        m_Player_Kick = m_Player.FindAction("Kick", throwIfNotFound: true);
        m_Player_OpenStats = m_Player.FindAction("OpenStats", throwIfNotFound: true);
        m_Player_StartDialog = m_Player.FindAction("StartDialog", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Attack;
    private readonly InputAction m_Player_Block;
    private readonly InputAction m_Player_GetSword;
    private readonly InputAction m_Player_GetAxe;
    private readonly InputAction m_Player_GetMace;
    private readonly InputAction m_Player_ExitToMenu;
    private readonly InputAction m_Player_Kick;
    private readonly InputAction m_Player_OpenStats;
    private readonly InputAction m_Player_StartDialog;
    public struct PlayerActions
    {
        private @MyPlayerInput m_Wrapper;
        public PlayerActions(@MyPlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Attack => m_Wrapper.m_Player_Attack;
        public InputAction @Block => m_Wrapper.m_Player_Block;
        public InputAction @GetSword => m_Wrapper.m_Player_GetSword;
        public InputAction @GetAxe => m_Wrapper.m_Player_GetAxe;
        public InputAction @GetMace => m_Wrapper.m_Player_GetMace;
        public InputAction @ExitToMenu => m_Wrapper.m_Player_ExitToMenu;
        public InputAction @Kick => m_Wrapper.m_Player_Kick;
        public InputAction @OpenStats => m_Wrapper.m_Player_OpenStats;
        public InputAction @StartDialog => m_Wrapper.m_Player_StartDialog;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Attack.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnAttack;
                @Block.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBlock;
                @Block.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBlock;
                @Block.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnBlock;
                @GetSword.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGetSword;
                @GetSword.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGetSword;
                @GetSword.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGetSword;
                @GetAxe.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGetAxe;
                @GetAxe.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGetAxe;
                @GetAxe.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGetAxe;
                @GetMace.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGetMace;
                @GetMace.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGetMace;
                @GetMace.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnGetMace;
                @ExitToMenu.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnExitToMenu;
                @ExitToMenu.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnExitToMenu;
                @ExitToMenu.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnExitToMenu;
                @Kick.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnKick;
                @Kick.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnKick;
                @Kick.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnKick;
                @OpenStats.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnOpenStats;
                @OpenStats.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnOpenStats;
                @OpenStats.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnOpenStats;
                @StartDialog.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnStartDialog;
                @StartDialog.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnStartDialog;
                @StartDialog.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnStartDialog;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @Block.started += instance.OnBlock;
                @Block.performed += instance.OnBlock;
                @Block.canceled += instance.OnBlock;
                @GetSword.started += instance.OnGetSword;
                @GetSword.performed += instance.OnGetSword;
                @GetSword.canceled += instance.OnGetSword;
                @GetAxe.started += instance.OnGetAxe;
                @GetAxe.performed += instance.OnGetAxe;
                @GetAxe.canceled += instance.OnGetAxe;
                @GetMace.started += instance.OnGetMace;
                @GetMace.performed += instance.OnGetMace;
                @GetMace.canceled += instance.OnGetMace;
                @ExitToMenu.started += instance.OnExitToMenu;
                @ExitToMenu.performed += instance.OnExitToMenu;
                @ExitToMenu.canceled += instance.OnExitToMenu;
                @Kick.started += instance.OnKick;
                @Kick.performed += instance.OnKick;
                @Kick.canceled += instance.OnKick;
                @OpenStats.started += instance.OnOpenStats;
                @OpenStats.performed += instance.OnOpenStats;
                @OpenStats.canceled += instance.OnOpenStats;
                @StartDialog.started += instance.OnStartDialog;
                @StartDialog.performed += instance.OnStartDialog;
                @StartDialog.canceled += instance.OnStartDialog;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnAttack(InputAction.CallbackContext context);
        void OnBlock(InputAction.CallbackContext context);
        void OnGetSword(InputAction.CallbackContext context);
        void OnGetAxe(InputAction.CallbackContext context);
        void OnGetMace(InputAction.CallbackContext context);
        void OnExitToMenu(InputAction.CallbackContext context);
        void OnKick(InputAction.CallbackContext context);
        void OnOpenStats(InputAction.CallbackContext context);
        void OnStartDialog(InputAction.CallbackContext context);
    }
}
